apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
data:
  db-user: cm9vdA==
  db-password: cm9vdA==
  db-name: Y29sb3I=
  db-host: aG9zdC5kb2NrZXIuaW50ZXJuYWw=
  db-port: MTMzMDQ=
